= Spring Boot
:hp-tags: java, spring boot

Spring Boot is framework that makes it super easy to setup and run a java spring application. It makes all neccessary configurations by using default implementations for all parts of application: 

* Application Configuration
* JPA implementation - Hibernate including transaction management, ... etc.
* Tempating engine
* ... and more

This concept is called *Convention over Configuration*.
Of course these defaults can be easily re-configured.

On top of that we get:

 * Embedded Tomcat (or other) server to easily run our web app - as easily as `java -jar app.jar`

TODO:
benefits in production


== Setup
To setup Spring Boot in our application using maven we need these steps:

=== 1. Setup parent POM
[source,xml]
----
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.4.3.RELEASE</version>
</parent>
----

=== 2. Add entrypoint
You can either use in any class `@EnableAutoConfiguration` annotation for Spring Boot to setup all configurations for all dependencies or use application entry point with `@SpringBootApplication` annotation:

[source,java]
----
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
----

=== 3. Set other dependencies in POM
If our application will use web we can add dependency on Spring MVC:
[source,xml]
----
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-web</artifactId>
</dependency>
----
If we need persistence we can add dependency on Spring Data and JPA:
[source,xml]
----
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
----
