= Spring Boot
:hp-tags: java, spring, spring boot

Spring Boot is framework that makes it super easy to setup and run a java spring application. It makes all neccessary configurations by using default implementations for all parts of application: 

* Application Configuration
* JPA implementation - Hibernate including transaction management, ... etc.
* Tempating engine
* ... and more

This concept is called *Convention over Configuration*.
Of course these defaults can be easily re-configured.

On top of that we get embedded Tomcat (or other) server to easily run our web app - as easily as `java -jar app.jar` or `mvn spring-boot:run`. Also there are some options for monitoring in production.

== Setup
To setup Spring Boot in our application using maven we need these steps:

=== 1. Setup parent POM
[source,xml]
----
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.4.3.RELEASE</version>
</parent>
----
From now on you can use everything from Spring Core e.g `@Autowired`.

=== 2. Add entrypoint
Now for Spring Boot to setup all configurations for all dependencies use application entry point with `@SpringBootApplication` annotation:

[source,java]
----
@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
----
Now Spring Boot is setup and your application would start.

=== 3. Add web dependency in POM
If our application will use web we can add dependency on Spring MVC:
[source,xml]
----
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-web</artifactId>
</dependency>
----
And then you can create right away Controller e.g. `@RestController` with `@RequestMapping` methods to create REST API:
[source,java]
----
@RestController
public class QuestionController {

    @RequestMapping("/questions/{id}")
    Question getQuestion(@PathVariable Integer id) {
        return new Question(id);
    }
}
----
When application starts it will start immediately serving this REST API with embedded Tomcat at this address:
[source,java]
----
http://localhost:8080/questions/12
----

=== 4. Add persistence dependency in POM
Usually we need some persistence so we can add dependency on Spring Data and JPA:
[source,xml]
----
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
----
Now we create our model with JPA annotations as usual. All these `@Entity`, `@Id`, `@ManyToOne`, `@OneToMany`, ...

We also have included Spring Data by this dependency so we can start using it with all features it provides. We can create reporitory only by providing this interface:
[source,java]
----
public interface QuestionRepository extends JpaRepository<Question, Integer> {}
----
Yes that's right no methods, no implementation, everything will be setup by Spring Data library. We would just autowire it and start using it:
[source,java]
----
@RestController
public class QuestionController {

    @Autowired
    QuestionRepository repo;

    @RequestMapping("/questions")
    @JsonView(QuestionListView.class)
    List<Question> getAll() {
        return repo.findAll();
    }

    @RequestMapping("/questions/{id}")
    Question getQuestion(@PathVariable Integer id) {
        return repo.findOne(id);
    }
}
----
Last step is to add maven dependency to our DB driver and provide datasource properties for connection to DB.

And that's all, we have working persistence with minimal effort.

Whole application code is available at gihub: https://github.com/ovo-6/samples/tree/master/poll-spring-boot-react

== Conclusion
For quick development java application using Spring, for creating POCs, anywhere you need quick start this is great framework.

Questions is whether it is still usable for more complicated projects where we want to override large number of parts. 
