= Lombok
:hp-tags: java, lombok

There are not many java libraries that would elegantly solve some major shortcomings of java programs, but https://projectlombok.org[project lombok] is one of them.

It provides set of useful annotations solving different set of problems but common theme is to reduce https://en.wikipedia.org/wiki/Boilerplate_code[boiler plate code].

== Setup
We need to add maven dependency:
[source,html]
----
<dependency>
   <groupId>org.projectlombok</groupId>
   <artifactId>lombok</artifactId>
   <version>1.16.12</version>
</dependency>
----
Also if we use features that are adding new methods to objects we need to install IDE plugin, in my case for https://plugins.jetbrains.com/idea/plugin/6317-lombok-plugin[IDEA].

Now we can use of benefits new lombok annotations it provides.

== @NotNull
One of great annotations to reduce boilerplate is to reduce null checks in every method that requires input that is not null.

We can do it like this with lombok:
[source,java]
----
public class Person {    
    private String name;    

    public void setFirstNameLastName(@NonNull  String firstName, @NonNull String lastName ) {
        this.name = firstName + " " + lastName;
    }
}
----
Now when we call the method with some of arguments `null` it will throw runtime exception with argument name:
[source,txt]
----
Exception in thread "main" java.lang.NullPointerException: firstName
at com.ovo.domain.Person.setFirstNameLastName(Person.java:13)
----
We don't have to mess with null checks. Code can be clean and we reduce possibility to introduce bug in out null checks. There are other options in java how to do the same but lombok does it in nice and clean way.

== @Data and related
When we annotate class with `@Data` annotation it effectively adds other lombok annotations:  `@Getter`, `@Setter`, `@ToString`, `@EqualsAndHashCode` and `@RequiredArgsConstructor`.
Basically it enables you to write java classes with fields only and getters and setters for all fields, `toString()`, `equals()` and `hashCode()` methods are automatically generated.

Consider this class:
[source,java]
----
@Data
public class Person {
    private final Long id;
    private String name;
    private Person manager;    
}
----
Due to `@RequiredArgsConstructor` all `final` fields are part of constructor so you will crate instance with `id` argument like this:
[source,java]
----
Person joe = new Person(456L);
----
Then we have setters for `name` and `manager` fields:
[source,java]
----
joe.setName("joe");
joe.setManager(manager);
System.out.println(joe);
----

And finally we have `toString()` that will produce by default this output:
[source,txt]
----
Person(id=456, name=joe, manager=Person(id=123, name=boss, manager=null))
----

Also we have implementation of `equals()` and `hashCode()` using all fields.

If we are not happy what fields got included into previously mentioned generated methods lombok has configuration options to exclude unwanted fields and further control behaviour.


== @Builder
Another great feature is possibility of creating builders with https://en.wikipedia.org/wiki/Fluent_interface[fluent interface].

We just annotate our pojo class:
[source,java]
----
@Data
@Builder
public class Team {
    private String name;
    @Singular private List<Person> members;
}
----
And then we can build our instance:
[source,java]
----
Team team = Team.builder().name("A Team").member(new Person(1L)).member(new Person(2L)).build();
----
There is one special annotation - `@Singular` that enables adding entries to collection by subsequent calls to the same method. Nice :)

== Logging

== Conclusion
Lombok is nice library and it is worth using even when you use only one annotation from it. 

== References
* Offical pages - https://projectlombok.org
* Sample app showing usage - https://github.com/ovo-6/samples/tree/master/lombok
* IntelliJ IDEA plugin - https://plugins.jetbrains.com/idea/plugin/6317-lombok-plugin