= Spring Boot
:hp-tags: java, spring boot

Spring Boot is framework that makes it super easy to setup and run a java spring application. It makes all neccessary configurations by using default implementations for all parts of application: 

* Application Configuration
* JPA implementation - Hibernate including transaction management, ... etc.
* Tempating engine
* ... and more

This concept is called *Convention over Configuration*.
Of course these defaults can be easily re-configured.

On top of that we get:

 * Embedded Tomcat (or other) server to easily run our web app - as easily as `java -jar app.jar`

TODO:
benefits in production


== Setup
To setup Spring Boot in our application using maven we need these steps:

=== 1. Setup parent POM
[source,xml]
----
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.4.3.RELEASE</version>
</parent>
----

=== 2. Add entrypoint
Now for Spring Boot to setup all configurations for all dependencies use application entry point with `@SpringBootApplication` annotation:

[source,java]
----
@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
----
Now Spring Boot is setup and your application would start.

=== 3. Add web dependency in POM
If our application will use web we can add dependency on Spring MVC:
[source,xml]
----
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-web</artifactId>
</dependency>
----
And then you can create right away Controller e.g. `@RestController` with `@RequestMapping` methods to create REST API:
[source,java]
----
@RestController
public class QuestionController {

    @RequestMapping("/questions/{id}")
    Question getQuestion(@PathVariable Integer id) {
        return new Question(id);
    }
}
----
When application starts it will start immediately serving this REST API with embedded Tomcat in this address:
[source,java]
----
http://localhost:8080/questions/12
----

=== 4. Add persistence dependency in POM
Usually we need some persistence so we can add dependency on Spring Data and JPA:
[source,xml]
----
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
----
