= Cucumber
:hp-tags: java, testing

Cucumber is tool for creating acceptance tests by capturing requirements for system to be implemented and also for tracking the state of implementation in automated manner.

Basically someone (e.g. product owner) defines requirements in specific areas of functionality in plain english sentences. This is example:

[source,txt]
----
Scenario: Invalid login
  When admin logs in with password invalid
  Then the server should handle it and return a UNAUTHORIZED status
----

Then someone else (e.g. developer) will implement code behind these sentences that will call actual implementation to prove it is really implemented.

In our test we will use `@When` annotation with regural expression to parse the string with condition.
[source,java]
----
	@When("^(.*) logs in with password (.*)$")
    public void login(String username, String password) throws Throwable {
        AccountCredentials admin = new AccountCredentials();
        admin.setUsername(username);
        admin.setPassword(password);
        response = this.restTemplate.postForEntity("/login", admin, String.class);
    }
----

This code will create http post request for login with user and password to login endpoint. The response is saved to field that is used later in `@Then` statement:

[source,java]
----
    @Then("^no auth token should be returned$")
    public void no_auth_token_should_be_returned() throws Throwable {
        assertThat(response.getHeaders().get("Authorization")).isNullOrEmpty();
    }
----

This part only validates requirement written in sentence by checking response saved in field.

We can also add multiple statements by 'And` keyword to create more complex requirements.

Example of working test in conjunction with spring boot test can be seen here:
https://github.com/ovo-6/samples/blob/master/expenses/src/test/java/com/ovo6/expenses/acceptance/StepDefs.java

Tests definitions file:
https://github.com/ovo-6/samples/blob/master/expenses/src/test/resources/cucumber/login.feature

== Conclusion
Cucumber provides benefit of formalizing acceptance tests. On the other hand in more complex scenarios it may impose difficulties by creating such automated tests. Also the value of those tests is questionable when we have functionality covered by unit tests it may be seen as double investment.