= Spring Data
:hp-tags: java, spring, spring data

Spring Data is library that simplifies work with data storage. I'll focus on JPA repository features.

== Adding to project
When using Spring Boot we can simply add dependency on Spring Data and JPA:
[source,xml]
----
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
----

== Dynamic query derivation from repository method names
When we create repository that extends from `JpaRepository` or `CrudRepository` (non JPA) we inherit all the basic operations for creating, updating and deleting.
Beside that we can create method in this interface and based on method name Spring Data framework will generate JPA query.

Take this example:

[source,java]
----
public interface AnswerRepository extends JpaRepository<Answer, Integer> {

    List<Answer> findByQuestion(Question question);
}
----
Framework identifies `findBy{Fieldname}` method using camel-case and creates automatically implementation for this interface method.
It will generate something like this HQL query `SELECT * from Answer join Question q where q.id = :questionId`, where `questionId` is taken from input parameter as `question.getId()`.

Also it provides features like sorting and paging out of the box. You only add additional parameter `Pageable` or `Sort` in your method signature.
[source,java]
----
    List<Answer> findByQuestion(Question question, Pageable pageable);
}
----

You can filter by multiple fields, do ingore-case search and other stuff as described in https://docs.spring.io/spring-data/jpa/docs/current/reference/html[documentation].

== Support for transparent auditing (created, last changed)
To enable auditing you just add this one annotation to your config class `@EnableJpaAuditing`.

Then you can annotate field by one of `@CreatedBy`, `@LastModifiedBy` to capture the user who created or modified the entity
or use `@CreatedDate` or `@LastModifiedDate` to capture the point in time this happened.



== References
* Documentation - https://docs.spring.io/spring-data/jpa/docs/current/reference/html
* Sample Implementation - https://github.com/ovo-6/samples/blob/master/poll-spring-boot-react/src/com/ovo6/poll/repo/AnswerRepository.java