= Go
:hp-tags: go, golang

Go is new programming language created by Google. Because it runs fast and creates small single executable files with all dependencies inside it is ideal for microservices in docker containers.

== Example Program
Let's go straight to the business and create some service providing list of users as json:

[source,go]
----
package main

import (
    "fmt"
    "net/http"
    "encoding/json"
)

type User struct {
    Id int
    Name string
    Email string
    password string // first char lowercase -> not visible from outside
}

var users [3]User // global variable - array with 3 users

func handler(w http.ResponseWriter, r *http.Request) {
    b, _ := json.Marshal(users)
    fmt.Fprintf(w, string(b))
}

func main() {
    users[0] = User{1, "joe", "joe@yahoo.com", "xyz"}
    users[1] = User{2, "mike", "mike@gmail.com", "xyz"}
    users[2] = User{3, "frank", "frank@email.com", "xyz"}

    http.HandleFunc("/users", handler) // assign function `handler` to serve requests for `/users`
    http.ListenAndServe(":8086", nil) // start server on port 8086
}
----

When we save this to file named `main.go` and run it by command `go run main.go` it will start serving requests.

Now we can simply go to `http://localhost:8086/users` and we should see our arrays of users serialized to json:
[source]
----
[{"Id":1,"Name":"joe","Email":"joe@yahoo.com"},{"Id":2,"Name":"mike","Email":"mike@gmail.com"},{"Id":3,"Name":"frank","Email":"frank@email.com"}]
----
 
== Go Feaures
* statically typed language - compiler can check types (like in Java)
* go routines - simple way how to provide concurrency
* functions can return multiple values
* array slices - we don't work with whole arrays but only subparts called slices
* `go test` - run all tests - functions starting with `Test`

== Conclusion
After one day of playing with Go it looks promising with some nice language features. Question is whether user comunity will create enough libraries since the language is still quite new. Also it would be nice to measure performance between Go and let say Java microservice if learning new language is worth it.

== References
* Official Pages - https://golang.org/
* Source of this example - https://github.com/ovo-6/samples/blob/master/go/src/gowiki/users.go